# Generated by Django 3.1.3 on 2020-12-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201201_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otherincome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savingsbank', models.CharField(blank=True, max_length=50)),
                ('deposit', models.CharField(blank=True, max_length=50)),
                ('interest_income', models.CharField(blank=True, max_length=50)),
                ('any_other_interest_income', models.CharField(blank=True, max_length=50)),
                ('any_other_income', models.CharField(blank=True, max_length=50)),
                ('dividend_income', models.CharField(blank=True, max_length=50)),
                ('dividend_income_from_Mutual_fund', models.CharField(blank=True, max_length=50)),
                ('ppf', models.CharField(blank=True, max_length=50)),
                ('any_other', models.CharField(blank=True, max_length=50)),
                ('gross_agriculture', models.CharField(blank=True, max_length=50)),
                ('expenditure_on_agriculture', models.CharField(blank=True, max_length=50)),
                ('unabsorbed_agriculture_loss', models.CharField(blank=True, max_length=50)),
                ('agriculture_land_details1', models.CharField(blank=True, max_length=50)),
                ('agriculture_land_details2', models.CharField(blank=True, max_length=50)),
                ('agriculture_land_details3', models.CharField(blank=True, max_length=50)),
                ('agriculture_land_details4', models.CharField(blank=True, max_length=50)),
                ('agriculture_land_details5', models.CharField(blank=True, max_length=50)),
                ('agriculture_land_details6', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
