# Generated by Django 3.1.3 on 2020-12-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_otherincome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherincome',
            name='agriculture_land_details6',
        ),
    ]
