# Generated by Django 3.1.3 on 2020-12-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_otherincome_agriculture_land_details6'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_House_Property', models.CharField(blank=True, max_length=50)),
                ('Interest_paid_on_loan_for_this_house_property', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('Total_interest_amount_paid_during_the_pre_construction_period', models.CharField(blank=True, max_length=50)),
                ('Same_as_the_address_in_Personal_Info', models.CharField(blank=True, max_length=50)),
                ('flat_num', models.CharField(blank=True, max_length=50)),
                ('premise_name', models.CharField(blank=True, max_length=50)),
                ('road_name', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('town_name', models.CharField(blank=True, max_length=50)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('country_name', models.CharField(blank=True, max_length=50)),
                ('Name_of_Co_Owner1', models.CharField(blank=True, max_length=50)),
                ('pan_of_Co_Owner1', models.CharField(blank=True, max_length=50)),
                ('percentage_of_Co_Owner1', models.CharField(blank=True, max_length=50)),
                ('Name_of_Co_Owner2', models.CharField(blank=True, max_length=50)),
                ('pan_of_Co_Owner2', models.CharField(blank=True, max_length=50)),
                ('percentage_of_Co_Owner2', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
