# Generated by Django 3.1.3 on 2020-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_house_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Investment_for_Section', models.CharField(blank=True, max_length=50)),
                ('Interest_earned_on_Savings_Bank_Account', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
