# Generated by Django 3.1.3 on 2020-12-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_more_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAN_of_Deductor', models.CharField(blank=True, max_length=50)),
                ('Name_of_Deductor', models.CharField(blank=True, max_length=50)),
                ('Total_Tax_Deducted', models.CharField(blank=True, max_length=50)),
                ('Tax_Deducted_claimed_for_this_year', models.CharField(blank=True, max_length=50)),
                ('Income_against_which_TDS_was_deducted', models.CharField(blank=True, max_length=50)),
                ('Type_of_Income', models.CharField(blank=True, max_length=50)),
                ('Financial_Year_in_which_TDS_was_deducted', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
